# core/workers/upload_worker.py
import asyncio
from pyrogram import Client
from core.state.queues import upload_queue
from core.state.models import Job, Stage
from core.state.persistence import write_trace
from core.pipeline.manager import transition_stage
from core.uploader.telegram import upload_video

async def upload_worker(app: Client, worker_id: int) -> None:
    """Background worker that pulls finished encodes and uploads them to Telegram."""
    print(f"🚀 Upload Worker {worker_id} online and waiting for jobs...")
    
    while True:
        job: Job = await upload_queue.get()
        
        write_trace(job.work_dir, f"[WORKER-UP-{worker_id}] Picked up job for uploading.")
        transition_stage(job, Stage.UPLOADING)
        
        try:
            # Locate the exact files generated by the FFmpeg sandbox
            enc_file = job.work_dir / f"{job.job_id}_enc.mp4"
            thumb_file = job.work_dir / f"{job.job_id}_thumb.jpg"
            
            if not enc_file.exists():
                raise FileNotFoundError("Encoded MP4 is missing from the working directory.")
                
            # The worker delegates the actual network execution to the engine
            success = await upload_video(app, job, enc_file, thumb_file)
            
            if success:
                write_trace(job.work_dir, f"[WORKER-UP-{worker_id}] ✅ Job fully completed!")
                transition_stage(job, Stage.DONE)
            else:
                write_trace(job.work_dir, f"[WORKER-UP-{worker_id}] ❌ Upload exhausted/failed.")
                transition_stage(job, Stage.FAILED)
                
        except Exception as e:
            write_trace(job.work_dir, f"[WORKER-UP-{worker_id}] Critical unhandled worker crash: {e}")
            transition_stage(job, Stage.FAILED)
            
        finally:
            upload_queue.task_done()
